# Species {orientation="columns" scrolling="true"}

## {.toolbar}

```{r}
selectInput("higherGeographySpecies", "Site:", sites_names)

selectInput("group", "Group:", groups_names)

selectInput("iucn", "IUCN category:", iucn_names)

```


## Row

```{r}
source("extensions/image-sidebar.R")
layout_column_wrap(
  width = 1,
  heights_equal = "row",
  conditionalPanel("(typeof input.clicked_image_id !== 'undefined' && input.clicked_image_id != '')", add_image_sidebar(
    span(textOutput("species_name"), id = "species-cont-name"),
    span(htmlOutput("species_links"), id = "species-cont-links"),
    span(textOutput("species_fb_common_names"), id = "species-cont-common"),
    span(htmlOutput("species_fb_content"), id = "species-cont-content"),
    div(reactable::reactableOutput("species_info"), style = "font-size:50%"),
    div(htmltools::tags$span(
      bslib::input_switch("spi_dna_col", "Color DNA", TRUE), 
      bslib::input_switch("spi_dna_back", "Background DNA", FALSE)
        ),
      id = "species-add-control")
  )),
  htmlOutput("species_gallery")
)
```

