message("                 _\\|/_")
message("                 (o o)")
message("+-------------oOO-{_}-OOo-----------------+")
message("| Run prepare_data.R to update data files |")
message("+----------------------------------------*/")
